server:
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    # https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-jdbc_database_url
    url: ${JDBC_DATABASE_URL}

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO